Operation factory
php-bookkeeper/accounting pull request #5
Opened 2021-02-15 12:31 UTC by viktorprogger

2021-02-15 19:13 UTC, samdark approved these changes

2021-02-17 18:42 UTC, vjik requested changes

2021-02-17 18:42 UTC, vjik commented on src/Domain/Operation/TransactionCreationData.php
> +    public function getDebitAccount(): AccountIdInterface
```suggestion
    public function getDebitAccountId(): AccountIdInterface
```

2021-02-17 18:42 UTC, vjik commented on src/Domain/Operation/TransactionCreationData.php
> +    public function getCreditAccount(): AccountIdInterface
```suggestion
    public function getCreditAccountId(): AccountIdInterface
```

2021-02-18 08:26 UTC, merged